/**
 * Professional Environmental Monitoring Report Generator
 * Clean, data-focused air quality report format
 * Based on EPA and WHO air quality reporting standards
 */

import pdfMake from "pdfmake/build/pdfmake";
import pdfFonts from "pdfmake/build/vfs_fonts";
import { getAQICategory, POLLUTANT_LABELS, POLLUTANT_UNITS } from "./aqi";

// Initialize pdfmake fonts
(pdfMake as any).vfs = (pdfFonts as any).pdfMake?.vfs || {};

interface ReportData {
  cityName: string;
  state: string;
  region: string;
  currentAQI: number;
  pollutants: {
    pm25?: number;
    pm10?: number;
    no2?: number;
    so2?: number;
    o3?: number;
    co?: number;
  };
  historicalData: any[];
  forecastData: any[];
  mannKendall?: any;
  dataSource: string;
  generatedAt: Date;
  chartImages: {
    trendChart?: string;
    pollutantChart?: string;
    forecastChart?: string;
  };
}

export async function generateProfessionalPDF(data: ReportData): Promise<void> {
  const { category, color, description } = getAQICategory(data.currentAQI);

  // Convert hex color to RGB for pdfmake
  const hexToRgb = (hex: string) => {
    const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
    return result ? {
      r: parseInt(result[1], 16),
      g: parseInt(result[2], 16),
      b: parseInt(result[3], 16)
    } : { r: 0, g: 0, b: 0 };
  };

  const aqiColor = hexToRgb(color);
  const primaryBlue = { r: 59, g: 130, b: 246 }; // Professional blue
  const darkGray = { r: 31, g: 41, b: 55 }; // Dark text
  const mediumGray = { r: 107, g: 114, b: 128 }; // Secondary text
  const lightGray = { r: 243, g: 244, b: 246 }; // Backgrounds
  const veryLightGray = { r: 229, g: 231, b: 235 }; // Table alternating rows

  // Build PDF document definition - Professional environmental report format
  const docDefinition: any = {
    pageSize: 'A4',
    pageMargins: [40, 50, 40, 50], // Standard margins
    header: (currentPage: number) => {
      if (currentPage === 1) return {}; // No header on cover
      return {
        margin: [40, 20, 40, 0],
        columns: [
          {
            text: 'Air Quality Monitoring Report',
            style: 'headerTitle',
            width: '*'
          },
          {
            text: `${data.cityName} | ${data.generatedAt.toLocaleDateString('en-IN')}`,
            style: 'headerInfo',
            width: 'auto',
            alignment: 'right'
          }
        ]
      };
    },
    footer: (currentPage: number, pageCount: number) => {
      if (currentPage === 1) return {}; // No footer on cover
      return {
        margin: [40, 0, 40, 20],
        columns: [
          {
            text: `AQIndia Platform`,
            style: 'footer',
            width: '*'
          },
          { 
            text: `Page ${currentPage} of ${pageCount}`, 
            style: 'footer', 
            width: 'auto', 
            alignment: 'right' 
          }
        ]
      };
    },
    content: [
      {
        stack: [
          { text: '', margin: [0, 0, 0, 100] }, // Space from top
          {
            text: 'AIR QUALITY MONITORING REPORT',
            style: 'coverTitle',
            margin: [0, 0, 0, 20]
          },
          {
            canvas: [
              { 
                type: 'line', 
                x1: 0, 
                y1: 0, 
                x2: 515, 
                y2: 0, 
                lineWidth: 3, 
                lineColor: `rgb(${primaryBlue.r},${primaryBlue.g},${primaryBlue.b})` 
              }
            ],
            margin: [0, 0, 0, 40]
          },
          {
            text: data.cityName.toUpperCase(),
            style: 'coverCity',
            margin: [0, 0, 0, 10]
          },
          {
            text: `${data.state}, ${data.region} Region`,
            style: 'coverSubtitle',
            margin: [0, 0, 0, 60]
          },
          {
            table: {
              widths: ['35%', '65%'],
              body: [
                [
                  { text: 'Report Date:', style: 'coverLabel' },
                  { text: data.generatedAt.toLocaleDateString('en-IN', { year: 'numeric', month: 'long', day: 'numeric' }), style: 'coverValue' }
                ],
                [
                  { text: 'Data Source:', style: 'coverLabel' },
                  { text: data.dataSource, style: 'coverValue' }
                ],
                [
                  { text: 'Current AQI:', style: 'coverLabel' },
                  { text: `${data.currentAQI} - ${category}`, style: 'coverValue', color: color, bold: true }
                ]
              ]
            },
            layout: 'noBorders',
            margin: [0, 0, 0, 80]
          },
          {
            text: 'Generated by AQIndia Platform',
            style: 'coverFooter',
            margin: [0, 0, 0, 5]
          },
          {
            text: data.generatedAt.toLocaleString('en-IN'),
            style: 'coverFooter'
          }
        ],
        pageBreak: 'after'
      },

      {
        stack: [
          { text: 'Executive Summary', style: 'sectionTitle' },
          {
            canvas: [
              { 
                type: 'line', 
                x1: 0, 
                y1: 0, 
                x2: 515, 
                y2: 0, 
                lineWidth: 2, 
                lineColor: `rgb(${primaryBlue.r},${primaryBlue.g},${primaryBlue.b})` 
              }
            ],
            margin: [0, 0, 0, 15]
          },
          {
            table: {
              widths: ['25%', '25%', '25%', '25%'],
              body: [
                [
                  { 
                    text: 'AQI', 
                    style: 'metricBoxHeader',
                    fillColor: `rgb(${primaryBlue.r},${primaryBlue.g},${primaryBlue.b})`,
                    color: 'white'
                  },
                  { 
                    text: 'CATEGORY', 
                    style: 'metricBoxHeader',
                    fillColor: `rgb(${primaryBlue.r},${primaryBlue.g},${primaryBlue.b})`,
                    color: 'white'
                  },
                  { 
                    text: 'PM2.5 (µg/m³)', 
                    style: 'metricBoxHeader',
                    fillColor: `rgb(${primaryBlue.r},${primaryBlue.g},${primaryBlue.b})`,
                    color: 'white'
                  },
                  { 
                    text: 'PM10 (µg/m³)', 
                    style: 'metricBoxHeader',
                    fillColor: `rgb(${primaryBlue.r},${primaryBlue.g},${primaryBlue.b})`,
                    color: 'white'
                  }
                ],
                [
                  { 
                    text: data.currentAQI.toString(), 
                    style: 'metricBoxValue', 
                    color: color, 
                    bold: true,
                    fontSize: 28 
                  },
                  { 
                    text: category, 
                    style: 'metricBoxValue', 
                    color: color,
                    bold: true,
                    fontSize: 16
                  },
                  { 
                    text: data.pollutants.pm25 ? data.pollutants.pm25.toFixed(1) : 'N/A', 
                    style: 'metricBoxValue',
                    fontSize: 16
                  },
                  { 
                    text: data.pollutants.pm10 ? data.pollutants.pm10.toFixed(1) : 'N/A', 
                    style: 'metricBoxValue',
                    fontSize: 16
                  }
                ]
              ]
            },
            layout: {
              hLineWidth: () => 0,
              vLineWidth: () => 0,
              paddingTop: () => 10,
              paddingBottom: () => 10
            },
            margin: [0, 0, 0, 15]
          },
          {
            text: description,
            style: 'bodyText',
            margin: [0, 10, 0, 0]
          }
        ],
        margin: [0, 0, 0, 20]
      },

      {
        stack: [
          { text: 'Current Air Quality Metrics', style: 'sectionTitle' },
          {
            canvas: [
              { 
                type: 'line', 
                x1: 0, 
                y1: 0, 
                x2: 515, 
                y2: 0, 
                lineWidth: 2, 
                lineColor: `rgb(${primaryBlue.r},${primaryBlue.g},${primaryBlue.b})` 
              }
            ],
            margin: [0, 0, 0, 15]
          },
          {
            table: {
              widths: ['16%', '16%', '16%', '16%', '16%', '20%'],
              headerRows: 1,
              dontBreakRows: true, // Prevent row splitting
              keepWithHeaderRows: 1, // Keep header with first row
              body: generateEnhancedPollutantTable(data.pollutants)
            },
            layout: {
              fillColor: (rowIndex: number) => {
                if (rowIndex === 0) return `rgb(${veryLightGray.r},${veryLightGray.g},${veryLightGray.b})`;
                return null;
              },
              hLineWidth: (i: number) => i === 0 || i === 1 ? 1.5 : 0.5,
              vLineWidth: () => 0.5,
              hLineColor: (i: number) => i === 0 || i === 1 ? `rgb(${primaryBlue.r},${primaryBlue.g},${primaryBlue.b})` : `rgb(${mediumGray.r},${mediumGray.g},${mediumGray.b})`,
              vLineColor: () => `rgb(${mediumGray.r},${mediumGray.g},${mediumGray.b})`,
              paddingTop: () => 8,
              paddingBottom: () => 8
            },
            margin: [0, 0, 0, 15]
          }
        ],
        margin: [0, 0, 0, 20]
      },

      ...(data.chartImages.trendChart ? [{
        stack: [
          { text: '30-Day AQI Trend', style: 'sectionTitle' },
          {
            canvas: [
              { 
                type: 'line', 
                x1: 0, 
                y1: 0, 
                x2: 515, 
                y2: 0, 
                lineWidth: 2, 
                lineColor: `rgb(${primaryBlue.r},${primaryBlue.g},${primaryBlue.b})` 
              }
            ],
            margin: [0, 0, 0, 15]
          },
          { 
            image: data.chartImages.trendChart, 
            width: 515, 
            height: 300, // Fixed height for consistency
            fit: [515, 300], // Maintain aspect ratio
            margin: [0, 0, 0, 10] 
          }
        ],
        margin: [0, 0, 0, 20]
      }] : []),

      ...(data.chartImages.pollutantChart ? [{
        stack: [
          { text: 'Pollutant Distribution', style: 'sectionTitle' },
          {
            canvas: [
              { 
                type: 'line', 
                x1: 0, 
                y1: 0, 
                x2: 515, 
                y2: 0, 
                lineWidth: 2, 
                lineColor: `rgb(${primaryBlue.r},${primaryBlue.g},${primaryBlue.b})` 
              }
            ],
            margin: [0, 0, 0, 15]
          },
          { 
            image: data.chartImages.pollutantChart, 
            width: 515, 
            height: 280,
            fit: [515, 280],
            margin: [0, 0, 0, 10] 
          }
        ],
        margin: [0, 0, 0, 20]
      }] : []),

      {
        stack: [
          { text: 'Historical Data (Last 10 Days)', style: 'sectionTitle' },
          {
            canvas: [
              { 
                type: 'line', 
                x1: 0, 
                y1: 0, 
                x2: 515, 
                y2: 0, 
                lineWidth: 2, 
                lineColor: `rgb(${primaryBlue.r},${primaryBlue.g},${primaryBlue.b})` 
              }
            ],
            margin: [0, 0, 0, 15]
          },
          {
            table: {
              widths: ['16%', '14%', '14%', '14%', '14%', '14%', '14%'],
              headerRows: 1,
              dontBreakRows: true, // CRITICAL: Prevent row splitting across pages
              keepWithHeaderRows: 1, // Keep header with first data row
              body: generateEnhancedHistoricalTable(data.historicalData)
            },
            layout: {
              fillColor: (rowIndex: number) => {
                if (rowIndex === 0) return `rgb(${veryLightGray.r},${veryLightGray.g},${veryLightGray.b})`;
                if (rowIndex % 2 === 0) return `rgb(${veryLightGray.r},${veryLightGray.g},${veryLightGray.b})`;
                return 'white';
              },
              hLineWidth: (i: number) => i === 0 || i === 1 ? 1.5 : 0.5,
              vLineWidth: () => 0.5,
              hLineColor: (i: number) => i === 0 || i === 1 ? `rgb(${primaryBlue.r},${primaryBlue.g},${primaryBlue.b})` : `rgb(${mediumGray.r},${mediumGray.g},${mediumGray.b})`,
              vLineColor: () => `rgb(${mediumGray.r},${mediumGray.g},${mediumGray.b})`,
              paddingTop: () => 6,
              paddingBottom: () => 6
            },
            margin: [0, 0, 0, 15]
          }
        ],
        margin: [0, 0, 0, 20]
      },

      ...(data.mannKendall ? [{
        stack: [
          { text: 'Statistical Trend Analysis', style: 'sectionTitle' },
          {
            canvas: [
              { 
                type: 'line', 
                x1: 0, 
                y1: 0, 
                x2: 515, 
                y2: 0, 
                lineWidth: 2, 
                lineColor: `rgb(${primaryBlue.r},${primaryBlue.g},${primaryBlue.b})` 
              }
            ],
            margin: [0, 0, 0, 15]
          },
          {
            table: {
              widths: ['25%', '25%', '25%', '25%'],
              headerRows: 1,
              dontBreakRows: true,
              keepWithHeaderRows: 1,
              body: [
                [
                  { 
                    text: 'Trend', 
                    style: 'tableHeader',
                    color: `rgb(${darkGray.r},${darkGray.g},${darkGray.b})`
                  },
                  { 
                    text: "Sen's Slope", 
                    style: 'tableHeader',
                    color: `rgb(${darkGray.r},${darkGray.g},${darkGray.b})`
                  },
                  { 
                    text: 'p-value', 
                    style: 'tableHeader',
                    color: `rgb(${darkGray.r},${darkGray.g},${darkGray.b})`
                  },
                  { 
                    text: 'Significant', 
                    style: 'tableHeader',
                    color: `rgb(${darkGray.r},${darkGray.g},${darkGray.b})`
                  }
                ],
                [
                  { 
                    text: data.mannKendall.trend.toUpperCase(), 
                    style: 'metricValue', 
                    bold: true, 
                    color: data.mannKendall.trend === 'increasing' ? '#dc2626' : '#16a34a',
                    fontSize: 13
                  },
                  { 
                    text: `${data.mannKendall.sens_slope?.toFixed(4)} AQI/day`, 
                    style: 'metricValue',
                    fontSize: 11
                  },
                  { 
                    text: data.mannKendall.p_value?.toFixed(4), 
                    style: 'metricValue',
                    fontSize: 11
                  },
                  { 
                    text: data.mannKendall.p_value < 0.05 ? 'Yes (p<0.05)' : 'No (p≥0.05)', 
                    style: 'metricValue', 
                    color: data.mannKendall.p_value < 0.05 ? '#16a34a' : '#6b7280',
                    bold: true,
                    fontSize: 11
                  }
                ]
              ]
            },
            layout: {
              fillColor: (rowIndex: number) => {
                if (rowIndex === 0) return `rgb(${veryLightGray.r},${veryLightGray.g},${veryLightGray.b})`;
                return null;
              },
              hLineWidth: (i: number) => i === 0 || i === 1 ? 1.5 : 0.5,
              vLineWidth: () => 0.5,
              hLineColor: (i: number) => i === 0 || i === 1 ? `rgb(${primaryBlue.r},${primaryBlue.g},${primaryBlue.b})` : `rgb(${mediumGray.r},${mediumGray.g},${mediumGray.b})`,
              vLineColor: () => `rgb(${mediumGray.r},${mediumGray.g},${mediumGray.b})`,
              paddingTop: () => 8,
              paddingBottom: () => 8
            },
            margin: [0, 0, 0, 15]
          }
        ],
        margin: [0, 0, 0, 20]
      }] : []),

      ...(data.forecastData && data.forecastData.length > 0 ? [{
        stack: [
          { text: '7-Day AQI Forecast', style: 'sectionTitle' },
          {
            canvas: [
              { 
                type: 'line', 
                x1: 0, 
                y1: 0, 
                x2: 515, 
                y2: 0, 
                lineWidth: 2, 
                lineColor: `rgb(${primaryBlue.r},${primaryBlue.g},${primaryBlue.b})` 
              }
            ],
            margin: [0, 0, 0, 15]
          },
          ...(data.chartImages.forecastChart ? [{ 
            image: data.chartImages.forecastChart, 
            width: 515,
            height: 280,
            fit: [515, 280],
            margin: [0, 0, 0, 15] 
          }] : []),
          {
            table: {
              widths: ['20%', '20%', '20%', '20%', '20%'],
              headerRows: 1,
              dontBreakRows: true,
              keepWithHeaderRows: 1,
              body: generateEnhancedForecastTable(data.forecastData)
            },
            layout: {
              fillColor: (rowIndex: number) => {
                if (rowIndex === 0) return `rgb(${veryLightGray.r},${veryLightGray.g},${veryLightGray.b})`;
                return rowIndex % 2 === 0 ? `rgb(${veryLightGray.r},${veryLightGray.g},${veryLightGray.b})` : 'white';
              },
              hLineWidth: (i: number) => i === 0 || i === 1 ? 1.5 : 0.5,
              vLineWidth: () => 0.5,
              hLineColor: (i: number) => i === 0 || i === 1 ? `rgb(${primaryBlue.r},${primaryBlue.g},${primaryBlue.b})` : `rgb(${mediumGray.r},${mediumGray.g},${mediumGray.b})`,
              vLineColor: () => `rgb(${mediumGray.r},${mediumGray.g},${mediumGray.b})`,
              paddingTop: () => 7,
              paddingBottom: () => 7
            },
            margin: [0, 0, 0, 15]
          }
        ],
        margin: [0, 0, 0, 20]
      }] : []),

      {
        stack: [
          { text: 'Health Advisory', style: 'sectionTitle' },
          {
            canvas: [
              { 
                type: 'line', 
                x1: 0, 
                y1: 0, 
                x2: 515, 
                y2: 0, 
                lineWidth: 2, 
                lineColor: `rgb(${primaryBlue.r},${primaryBlue.g},${primaryBlue.b})` 
              }
            ],
            margin: [0, 0, 0, 15]
          },
          ...generateEnhancedHealthAdvisory(data.currentAQI, category)
        ],
        margin: [0, 0, 0, 20]
      }
    ],

    // Professional styles - Clean, data-focused design (using pdfmake built-in fonts)
    styles: {
      // Cover page styles
      coverTitle: { fontSize: 28, bold: true, color: `rgb(${darkGray.r},${darkGray.g},${darkGray.b})`, alignment: 'center' },
      coverCity: { fontSize: 32, bold: true, color: `rgb(${primaryBlue.r},${primaryBlue.g},${primaryBlue.b})`, alignment: 'center' },
      coverSubtitle: { fontSize: 16, color: `rgb(${mediumGray.r},${mediumGray.g},${mediumGray.b})`, alignment: 'center' },
      coverLabel: { fontSize: 11, bold: true, color: `rgb(${darkGray.r},${darkGray.g},${darkGray.b})`, margin: [0, 3, 0, 3] },
      coverValue: { fontSize: 11, color: `rgb(${darkGray.r},${darkGray.g},${darkGray.b})`, margin: [0, 3, 0, 3] },
      coverFooter: { fontSize: 10, color: `rgb(${mediumGray.r},${mediumGray.g},${mediumGray.b})`, alignment: 'center' },
      
      // Header/Footer styles
      headerTitle: { fontSize: 10, bold: true, color: `rgb(${primaryBlue.r},${primaryBlue.g},${primaryBlue.b})` },
      headerInfo: { fontSize: 9, color: `rgb(${mediumGray.r},${mediumGray.g},${mediumGray.b})`, italics: true },
      footer: { fontSize: 8, color: `rgb(${mediumGray.r},${mediumGray.g},${mediumGray.b})`, italics: true },
      
      // Section styles
      sectionTitle: { fontSize: 16, bold: true, color: `rgb(${darkGray.r},${darkGray.g},${darkGray.b})`, margin: [0, 0, 0, 5] },
      subSectionTitle: { fontSize: 12, bold: true, color: `rgb(${primaryBlue.r},${primaryBlue.g},${primaryBlue.b})`, margin: [0, 0, 0, 5] },
      
      // Table styles - NO WHITE TEXT (white background = invisible!)
      tableHeader: { fontSize: 10, bold: true, color: `rgb(${darkGray.r},${darkGray.g},${darkGray.b})`, alignment: 'center' },
      metricBoxHeader: { fontSize: 9, bold: true, color: `rgb(${darkGray.r},${darkGray.g},${darkGray.b})`, alignment: 'center' },
      metricBoxValue: { fontSize: 14, alignment: 'center', margin: [0, 5, 0, 5] },
      
      // Text styles
      bodyText: { fontSize: 11, color: `rgb(${darkGray.r},${darkGray.g},${darkGray.b})`, lineHeight: 1.5 },
      bulletList: { fontSize: 10.5, color: `rgb(${darkGray.r},${darkGray.g},${darkGray.b})`, lineHeight: 1.5, margin: [10, 3, 0, 3] }
    },

    // Default styles - using pdfmake built-in Roboto font
    defaultStyle: {
      fontSize: 11,
      color: `rgb(${darkGray.r},${darkGray.g},${darkGray.b})`,
      lineHeight: 1.5
    }
  };

  // Generate and download PDF
  pdfMake.createPdf(docDefinition).download(`AQIndia_Report_${data.cityName}_${data.generatedAt.toISOString().slice(0, 10)}.pdf`);
}

// Helper: Generate enhanced pollutant table with AQI scale reference
function generateEnhancedPollutantTable(pollutants: any): any[][] {
  const darkTextColor = '#1F2937'; // Dark gray for visibility on white background
  const rows = [
    [
      { text: 'PM2.5', style: 'tableHeader', color: darkTextColor },
      { text: 'PM10', style: 'tableHeader', color: darkTextColor },
      { text: 'NO₂', style: 'tableHeader', color: darkTextColor },
      { text: 'SO₂', style: 'tableHeader', color: darkTextColor },
      { text: 'O₃', style: 'tableHeader', color: darkTextColor },
      { text: 'CO', style: 'tableHeader', color: darkTextColor }
    ],
    [
      { text: pollutants.pm25 ? `${pollutants.pm25.toFixed(1)}` : 'N/A', style: 'metricValue', bold: true, fontSize: 12 },
      { text: pollutants.pm10 ? `${pollutants.pm10.toFixed(1)}` : 'N/A', style: 'metricValue', bold: true, fontSize: 12 },
      { text: pollutants.no2 ? `${pollutants.no2.toFixed(1)}` : 'N/A', style: 'metricValue', bold: true, fontSize: 12 },
      { text: pollutants.so2 ? `${pollutants.so2.toFixed(1)}` : 'N/A', style: 'metricValue', bold: true, fontSize: 12 },
      { text: pollutants.o3 ? `${pollutants.o3.toFixed(1)}` : 'N/A', style: 'metricValue', bold: true, fontSize: 12 },
      { text: pollutants.co ? `${pollutants.co.toFixed(2)}` : 'N/A', style: 'metricValue', bold: true, fontSize: 12 }
    ],
    [
      { text: 'µg/m³', style: 'metricValue', fontSize: 9, italics: true },
      { text: 'µg/m³', style: 'metricValue', fontSize: 9, italics: true },
      { text: 'µg/m³', style: 'metricValue', fontSize: 9, italics: true },
      { text: 'µg/m³', style: 'metricValue', fontSize: 9, italics: true },
      { text: 'µg/m³', style: 'metricValue', fontSize: 9, italics: true },
      { text: 'mg/m³', style: 'metricValue', fontSize: 9, italics: true }
    ]
  ];
  return rows;
}

// Helper: Generate enhanced historical data table with color-coded AQI
function generateEnhancedHistoricalTable(data: any[]): any[][] {
  const darkTextColor = '#1F2937'; // Dark gray for visibility
  const header = [
    { text: 'Date', style: 'tableHeader', color: darkTextColor },
    { text: 'AQI', style: 'tableHeader', color: darkTextColor },
    { text: 'PM2.5', style: 'tableHeader', color: darkTextColor },
    { text: 'PM10', style: 'tableHeader', color: darkTextColor },
    { text: 'NO₂', style: 'tableHeader', color: darkTextColor },
    { text: 'Temp (°C)', style: 'tableHeader', color: darkTextColor },
    { text: 'Humidity (%)', style: 'tableHeader', color: darkTextColor }
  ];

  const rows = data.slice(0, 10).map(row => {
    const { color } = getAQICategory(row.aqi);
    return [
      { text: row.date, style: 'metricValue', fontSize: 9 },
      { text: row.aqi.toString(), style: 'metricValue', bold: true, color: color, fontSize: 11 },
      { text: row.pm25?.toFixed(1) ?? '—', style: 'metricValue', fontSize: 9 },
      { text: row.pm10?.toFixed(1) ?? '—', style: 'metricValue', fontSize: 9 },
      { text: row.no2?.toFixed(1) ?? '—', style: 'metricValue', fontSize: 9 },
      { text: row.temperature ? `${row.temperature.toFixed(1)}` : '—', style: 'metricValue', fontSize: 9 },
      { text: row.humidity ? `${row.humidity.toFixed(0)}` : '—', style: 'metricValue', fontSize: 9 }
    ];
  });

  return [header, ...rows];
}

// Helper: Generate enhanced forecast table with confidence intervals
function generateEnhancedForecastTable(data: any[]): any[][] {
  const darkTextColor = '#1F2937'; // Dark gray for visibility
  const header = [
    { text: 'Date', style: 'tableHeader', color: darkTextColor },
    { text: 'Predicted AQI', style: 'tableHeader', color: darkTextColor },
    { text: 'Category', style: 'tableHeader', color: darkTextColor },
    { text: 'Lower 80%', style: 'tableHeader', color: darkTextColor },
    { text: 'Upper 80%', style: 'tableHeader', color: darkTextColor }
  ];

  const rows = data.slice(0, 7).map(row => {
    const { category, color } = getAQICategory(row.predicted_aqi);
    return [
      { text: row.date, style: 'metricValue', fontSize: 9 },
      { text: row.predicted_aqi.toString(), style: 'metricValue', bold: true, color: color, fontSize: 11 },
      { text: category, style: 'metricValue', color: color, fontSize: 9 },
      { text: row.lower_80?.toString() ?? '—', style: 'metricValue', fontSize: 9 },
      { text: row.upper_80?.toString() ?? '—', style: 'metricValue', fontSize: 9 }
    ];
  });

  return [header, ...rows];
}

// Helper: Generate enhanced health advisory with structured formatting
function generateEnhancedHealthAdvisory(aqi: number, category: string): any[] {
  const advisories: Record<string, { general: string; recommendations: string[] }> = {
    'Good': {
      general: 'Air quality is considered satisfactory, and air pollution poses little or no risk.',
      recommendations: [
        'Ideal conditions for outdoor activities, jogging, and exercise',
        'Windows can be kept open for natural ventilation',
        'No special precautions needed for any population group',
        'Excellent day for outdoor sports and recreational activities'
      ]
    },
    'Moderate': {
      general: 'Air quality is acceptable; however, there may be a moderate health concern for a very small number of people who are unusually sensitive to air pollution.',
      recommendations: [
        'Sensitive individuals should consider reducing prolonged outdoor exertion',
        'People with respiratory conditions (asthma, bronchitis) should monitor symptoms',
        'Outdoor activities are generally safe for the general population',
        'Consider wearing a mask if you experience throat or eye irritation'
      ]
    },
    'Poor': {
      general: 'Everyone may begin to experience health effects; members of sensitive groups may experience more serious health effects.',
      recommendations: [
        'Wear N95 or N99 mask when going outdoors',
        'Avoid outdoor exercise — switch to indoor workouts or gym activities',
        'Keep windows and doors closed; use air purifier indoors',
        'Children, elderly, and pregnant women should minimize outdoor exposure',
        'Reduce use of vehicles to prevent further pollution'
      ]
    },
    'Very Poor': {
      general: 'Health alert: The risk of health effects is increased for everyone. More serious health effects for sensitive groups.',
      recommendations: [
        'Avoid all outdoor activities; stay indoors as much as possible',
        'Use N95/P100 mask if going outside is absolutely unavoidable',
        'Run air purifier continuously indoors with HEPA filter',
        'Consult doctor immediately if experiencing breathing difficulty, coughing, or chest tightness',
        'Avoid burning wood, garbage, or firecrackers',
        'Schools should cancel outdoor sports and assemblies'
      ]
    },
    'Severe': {
      general: 'Health warning of emergency conditions. The entire population is more likely to be affected.',
      recommendations: [
        'EMERGENCY: Do not go outside unless absolutely necessary',
        'Seal gaps in doors and windows with wet cloth or tape',
        'Use air purifier with HEPA filter in all occupied rooms',
        'Seek immediate medical attention for breathing problems, chest pain, or severe coughing',
        'Schools and offices should consider closure or work-from-home',
        'All outdoor events, construction, and industrial activities should be halted',
        'Keep emergency contact numbers handy (local hospital, ambulance)'
      ]
    }
  };

  const advisory = advisories[category] || advisories['Moderate'];
  const elements: any[] = [];

  // General advisory
  elements.push({
    text: advisory.general,
    style: 'bodyText',
    margin: [0, 0, 0, 15],
    italics: true
  });

  // Specific recommendations
  elements.push({
    text: 'Specific Recommendations:',
    style: 'subSectionTitle',
    margin: [0, 10, 0, 10]
  });

  advisory.recommendations.forEach(rec => {
    elements.push({
      text: `• ${rec}`,
      style: 'bulletList',
      margin: [0, 4, 0, 4]
    });
  });

  return elements;
}

// Old helper functions (kept for backward compatibility)
function generatePollutantTable(pollutants: any): any[][] {
  const rows = [
    [
      { text: 'PM2.5', style: 'tableHeader', fillColor: '#f8f9fa' },
      { text: 'PM10', style: 'tableHeader', fillColor: '#f8f9fa' },
      { text: 'NO₂', style: 'tableHeader', fillColor: '#f8f9fa' },
      { text: 'SO₂', style: 'tableHeader', fillColor: '#f8f9fa' },
      { text: 'O₃', style: 'tableHeader', fillColor: '#f8f9fa' }
    ],
    [
      { text: pollutants.pm25 ? `${pollutants.pm25.toFixed(1)} µg/m³` : 'N/A', style: 'metricValue' },
      { text: pollutants.pm10 ? `${pollutants.pm10.toFixed(1)} µg/m³` : 'N/A', style: 'metricValue' },
      { text: pollutants.no2 ? `${pollutants.no2.toFixed(1)} µg/m³` : 'N/A', style: 'metricValue' },
      { text: pollutants.so2 ? `${pollutants.so2.toFixed(1)} µg/m³` : 'N/A', style: 'metricValue' },
      { text: pollutants.o3 ? `${pollutants.o3.toFixed(1)} µg/m³` : 'N/A', style: 'metricValue' }
    ]
  ];
  return rows;
}

// Helper: Generate historical data table
function generateHistoricalTable(data: any[]): any[][] {
  const header = [
    { text: 'Date', style: 'tableHeader' },
    { text: 'AQI', style: 'tableHeader' },
    { text: 'PM2.5', style: 'tableHeader' },
    { text: 'PM10', style: 'tableHeader' },
    { text: 'NO₂', style: 'tableHeader' },
    { text: 'Temp', style: 'tableHeader' },
    { text: 'Humidity', style: 'tableHeader' }
  ];

  const rows = data.slice(0, 10).map(row => {
    const { color } = getAQICategory(row.aqi);
    return [
      { text: row.date, style: 'metricValue' },
      { text: row.aqi.toString(), style: 'metricValue', bold: true, color: color },
      { text: row.pm25?.toFixed(1) ?? '—', style: 'metricValue' },
      { text: row.pm10?.toFixed(1) ?? '—', style: 'metricValue' },
      { text: row.no2?.toFixed(1) ?? '—', style: 'metricValue' },
      { text: row.temperature ? `${row.temperature.toFixed(0)}°C` : '—', style: 'metricValue' },
      { text: row.humidity ? `${row.humidity.toFixed(0)}%` : '—', style: 'metricValue' }
    ];
  });

  return [header, ...rows];
}

// Helper: Generate forecast table
function generateForecastTable(data: any[]): any[][] {
  const header = [
    { text: 'Date', style: 'tableHeader' },
    { text: 'Predicted AQI', style: 'tableHeader' },
    { text: 'Category', style: 'tableHeader' },
    { text: 'Lower 80%', style: 'tableHeader' },
    { text: 'Upper 80%', style: 'tableHeader' }
  ];

  const rows = data.slice(0, 7).map(row => {
    const { category, color } = getAQICategory(row.predicted_aqi);
    return [
      { text: row.date, style: 'metricValue' },
      { text: row.predicted_aqi.toString(), style: 'metricValue', bold: true, color: color },
      { text: category, style: 'metricValue', color: color },
      { text: row.lower_80?.toString() ?? '—', style: 'metricValue' },
      { text: row.upper_80?.toString() ?? '—', style: 'metricValue' }
    ];
  });

  return [header, ...rows];
}

// Helper: Generate health advisory
function generateHealthAdvisory(aqi: number, category: string): any[] {
  const advisories: Record<string, string[]> = {
    'Good': [
      '✓ Air quality is satisfactory',
      '✓ Ideal for outdoor activities and exercise',
      '✓ Windows can be kept open for ventilation',
      '✓ No special precautions needed'
    ],
    'Moderate': [
      '⚠ Air quality is acceptable for most people',
      '⚠ Sensitive individuals should limit prolonged outdoor exertion',
      '⚠ Consider wearing a mask if you have respiratory conditions',
      '⚠ Monitor air quality before planning outdoor events'
    ],
    'Poor': [
      '⚠ Everyone may begin to experience health effects',
      '✗ Wear N95 mask when going outdoors',
      '✗ Avoid outdoor exercise — switch to indoor workouts',
      '✗ Keep windows closed and use air purifier',
      '✗ Children and elderly should stay indoors'
    ],
    'Very Poor': [
      '⚠ Health alert: everyone may experience serious health effects',
      '✗ Avoid all outdoor activities',
      '✗ Use N95/P100 mask if going outside is unavoidable',
      '✗ Run air purifier continuously indoors',
      '✗ Consult doctor if experiencing breathing difficulty'
    ],
    'Severe': [
      '⚠ EMERGENCY: Health warning of emergency conditions',
      '✗ Do not go outside under any circumstances',
      '✗ Seal gaps in doors and windows',
      '✗ Use air purifier with HEPA filter',
      '✗ Seek immediate medical attention for breathing problems'
    ]
  };

  const recommendations = advisories[category] || advisories['Moderate'];

  return recommendations.map(rec => ({
    text: rec,
    style: 'listItem',
    margin: [0, 3, 0, 3]
  }));
}
